apiVersion: v1
kind: Secret
metadata:
  name: librechat-credentials-env
  namespace: librechat
type: Opaque
stringData:
  MEILI_MASTER_KEY: 986af116cb6135931db537baa78d3ac607580d3f24adee6c10c70764ed1e5cf7
