apiVersion: v1
kind: Service
metadata:
  name: dev-librechat-service
  namespace: librechat
status:
  loadBalancer: {}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3080
      targetPort: http
  selector:
    app.kubernetes.io/instance: librechat
    app.kubernetes.io/name: librechat-librechat
  type: ClusterIP
